# Generated by Django 5.0.6 on 2024-06-16 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="customer_id",
            new_name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last4",
        ),
    ]
