# Generated by Django 5.0.7 on 2024-09-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_membership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backing",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionbill",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionnote",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionbill",
            name="bill_ptr",
        ),
        migrations.RemoveField(
            model_name="subscriptionnote",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="context",
            field=models.CharField(choices=[("booking", "Booking")], max_length=32),
        ),
        migrations.AlterField(
            model_name="locationemailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("admin_daily_update", "Admin Daily Update"),
                    ("guest_daily_update", "Guest Daily Update"),
                    ("invoice", "Invoice"),
                    ("receipt", "Booking Receipt"),
                    ("newbooking", "New Booking"),
                    ("pre_arrival_welcome", "Pre-Arrival Welcome"),
                    ("departure", "Departure"),
                ],
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.DeleteModel(
            name="SubscriptionBill",
        ),
        migrations.DeleteModel(
            name="SubscriptionNote",
        ),
    ]
